config/routes.rb
EventPlanner::Application.routes.draw do

  devise_for :users
  root 'events#index'
  match '/events/:id/delete', to: 'events#destroy', via: :delete, :as => :destroy_event
  resources :events, only: [:show, :new, :create, :edit, :update, :destroy]
  resources :users do
    resources :tickets, only: [:new, :create]
  end

  match '/my_events', to: 'tickets#show', via: :get
end

app/models/event.rb
class Event < ActiveRecord::Base

  validates :title, :content, :presence => true
  validates :title, :length => { :minimum => 1}
  validates :title, :uniqueness => true
end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
  belongs_to :user

  validates :quantity, :numericality => { :greater_than => 0}
end

app/models/user.rb
class User < ActiveRecord::Base
  mount_uploader :avatar, AvatarUploader

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :tickets

  validates :email, presence: true, uniqueness: { case_sensitive: false}
  validates_format_of :email,
                      with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i,
                      :message => "must be an email address",
                      on: :create
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def available_events
    @events = Event.all - my_events - booked_events - past_events
    @events.sort_by! {|a| a.date}
  end

  def my_events
    @events = []
    current_user.tickets.each do |ticket|
      @events << Event.find(ticket.event_id)
    end
    @events.sort_by! {|a| a.date}
  end

  def booked_events
    @events_all = Event.all
    @events_booked = []
    @events_all.each do |event|
      if event.tickets_avail == 0
        @events_booked << event
      end
    end
    @events_booked
  end

  def past_events
    @events_all = Event.all
    @past_events = []
    @events_all.each do |event|
      if event.date.to_s < Date.today.to_s
        @past_events << event
      end
    end
    @past_events
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:email, :password, :password_confirmation, :remember_me,
                                                            :avatar, :avatar_cache) }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:email, :password, :password_confirmation,
                                                                   :current_password, :avatar, :avatar_cache) }
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  before_action :authenticate_user!

  def index
    @events = available_events
  end

  def show
    @event = Event.find(params[:id])
    @my_events = my_events
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.create(event_params)
    @event.tickets_avail = @event.tickets_total

    if @event.save
      redirect_to root_path, :notice => "New Event Added"
    else
      render "new"
    end
  end

  def edit
    if !current_user.admin?
      redirect_to root_path
    end
    @event = Event.find(params[:id])
  end

  def update
    if !current_user.admin?
      redirect_to root_path
    end
    @event = Event.find(params[:id])
    if @event.update_attributes(event_params)
      redirect_to root_path, :notice => "Event Updated"
    else
      render "edit"
    end
  end

  def destroy
    if !current_user.admin?
      redirect_to root_path
    end
    Event.find(params[:id]).destroy
    redirect_to root_path, :notice => "Event Deleted"
  end

  def event_params
    params.require(:event).permit(:title, :event_type, :venue, :tickets_avail, :tickets_total, :content, :date);
  end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  def create
    @user = current_user
    @event = Event.find(ticket_params[:event_id])

    if ticket_params[:quantity].to_i <= 0
      flash[:notice] = 'Invalid number of tickets'
      redirect_to event_path(ticket_params[:event_id])
    elsif ticket_params[:quantity].to_i <= @event.tickets_avail.to_i
      @ticket = @user.tickets.create(ticket_params)
      @event.tickets_avail= @event.tickets_avail.to_i - ticket_params[:quantity].to_i
      @event.save
      redirect_to my_events_path
    else
      flash[:notice] = 'Not enough tickets available'
      redirect_to event_path(ticket_params[:event_id])
    end
  end

  def show
    @events = my_events
    @tickets = current_user.tickets
  end


  private
  def ticket_params
    params.require(:ticket).permit(:quantity, :event_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def create
    @user = User.create(user_params)

    if @user.save
      login @user
      flash[:success] = 'Thanks for registering'
      redirect_to root_url
    else
      render 'new'
    end
  end

  def new
    @user = User.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def is_active?(link_path)
    current_page?(link_path) ? 'active' : ''
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/common/_form_errors.html.erb
<% if object.errors.any? %>
    <ul id="form-errors">
      <% object.errors.full_messages.each do |message| %>
          <li><%= message %></li>
      <% end %>
    </ul>
<% end %>

app/views/common/_preview_events.html.erb
<div class="event_preview">

  <div style="float:left; padding-right:15px;">
    <%= link_to image_tag('defaultEvent.png'), preview_events %>
    <% if current_user.admin? %>
        <p>
          <%= button_to 'Edit', edit_event_path(preview_events.id), :method => :get %>
        </p>
    <% end %>
  </div>

  <div style="float:left;">
      <p class="title"><%= link_to preview_events.title, preview_events %></p>
      <p class="date"><%= preview_events.date.strftime('%A, %B %d at %l:%M %P') %></p>
      <div class="text"><%= simple_format(preview_events.content) %></div>

  </div>

  <div style="clear:both;"></div>
</div>

app/views/events/edit.html.erb
<%= provide(:title, 'EventPlanner: Edit Event') %>

<h1>Edit Event</h1>

<%= form_for @event do |form| %>
    <%= render 'common/form_errors', object: @event %>

    <p>
      <%= form.label :title %><br/>
      <%= form.text_field :title %>
    </p>

    <p>
      <%= form.label :date %><br/>
      <%= form.datetime_select :date, order: [:month, :day, :year, :hour, :minute] %>
    </p>

    <p>
      <%= form.label :event_type %><br/>
      <%= form.text_field :event_type %>
    </p>

    <p>
      <%= form.label :venue %><br/>
      <%= form.text_field :venue %>
    </p>

    <p>
      <%= form.label :tickets_total %><br/>
      <%= form.text_field :tickets_total %>
    </p>

    <p>
      <%= form.label :content %><br/>
      <%= form.text_area :content %>
    </p>

    <p>
      <%= form.submit "Update Event" %>
    </p>
<% end %>
<% if current_user.admin? %>
    <p>
      <%= button_to 'Delete', destroy_event_path(@event.id), :method => :delete %>
    </p>
<% end %>

app/views/events/index.html.erb
<%= provide(:title, 'EventPlanner') %>

<!--<h1>Featured Events</h1>-->
<%= render partial: 'common/preview_events', collection: @events %>

<% if current_user.admin? %>
    <p><%= link_to "Add a new event", new_event_path %></p>
<% end %>

app/views/events/new.html.erb
<%= provide(:title, 'EventPlanner: Add Event') %>

<div class="new_event">

  <h1>Add a new event</h1>

  <%= form_for @event do |form| %>
      <%= render 'common/form_errors', object: @event %>

      <p>
        <%= form.label :title %><br/>
        <%= form.text_field :title %>
      </p>

      <p>
        <%= form.label :date %><br/>
        <%= form.datetime_select :date, order: [:month, :day, :year, :hour, :minute] %>
      </p>

      <p>
        <%= form.label :event_type %><br/>
        <%= form.text_field :event_type %>
      </p>

      <p>
        <%= form.label :venue %><br/>
        <%= form.text_field :venue %>
      </p>

      <p>
        <%= form.label :tickets_total %><br/>
        <%= form.text_field :tickets_total %>
      </p>

      <p>
        <%= form.label :content %><br/>
        <%= form.text_area :content %>
      </p>

      <p>
        <%= form.submit "Add a new event", :id => 'commit' %>
      </p>
  <% end %>

</div>

app/views/events/show.html.erb
<%= provide(:title, @event.title) %>

<div class="event_detail">
  <p class="title"><%= @event.title %></p>

  <% if @event.date.year == Date.today.year %>
    <p class="date"><%= @event.date.strftime("%A, %B %-d at %l:%M %P") %></p>
  <% else %>
    <p class="date"><%= @event.date.strftime("%A, %B %-d, %Y at %l:%M %P") %></p>
  <% end %>

  <p class="type_venue"><%= @event.event_type %> at <%= @event.venue %></p>

  <div class="text"><%= simple_format(@event.content) %></div>

  <div class="book_form">
    <% if @my_events.include?(@event) %>
        <p>
          You already have tickets for this event!
        </p>
    <% else %>
        <%= form_for([current_user, current_user.tickets.build]) do |form| %>
            <%= form.hidden_field :event_id, :value => @event.id %>
            <span>
              <%= form.label :quantity %><br>
            </span>
            <span>
              <%= form.text_field :quantity, :value => '1' %>
            </span>
            <span>
              <%= form.submit 'Book', {:class => 'button', :id => 'commit'} %>
            </span>
        <% end %>
    <% end %>
  </div>
  <p class="tickets"><%= @event.tickets_avail %> out of <%= @event.tickets_total %> tickets available</p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) %></title>
  <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div id="cssmenu">
  <ul>
    <div id="logo">
      <li class="logo">
        <%= image_tag('logo.png') %>
      </li>
    </div>
    <div id="left">
      <% if user_signed_in? %>
          <li class="<%= is_active?(my_events_path) %>">
            <%= link_to 'My Events', my_events_path, :id => 'my_events' %>
          </li>
          <li class="<%= is_active?(root_path) %>">
            <%= link_to 'Featured Events', root_path %>
          </li>
          <li class="<%= is_active?(edit_user_registration_path) %>">
            <%= link_to 'Settings', edit_user_registration_path, :id => 'settings' %>
          </li>
          <li>
            <%= link_to 'Sign Out', destroy_user_session_path, method: 'delete', :id => 'sign_out' %>
          </li>
      <% else %>
          <li class="<%= is_active?(new_user_registration_path) %>">
            <%= link_to 'Register', new_user_registration_path %>
          </li>
          <li class="<%= is_active?(new_user_session_path) %>">
            <%= link_to 'Sign in', new_user_session_path %>
          </li>
      <% end %>
    </div>
    <div id="right">
      <% if user_signed_in? %>
          <li id="email">
            <%= current_user.email %>
          </li>
          <li>
            <% if current_user.avatar.url.blank? %>
                <%= image_tag('defaultAvatar.jpg') %>
            <% else %>
                <%= image_tag(current_user.avatar.url) %>
            <% end %>
          </li>
      <% end %>
    </div>
  </ul>
</div>
<!-- end nav -->

<div id="content">

  <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
  <% end %>
  <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
  <% end %>

  <%= yield %>

</div>
<!-- end content -->

<div id="footer">
  &copy; EventPro <%= Date.today.year %>
</div>
<!-- end footer -->
</div>
<!-- end container -->

</body>
</html>

app/views/tickets/show.html.erb
<!--<h1>My Events</h1>-->
<% if !@tickets.empty? %>
    <% @events.each do |event| %>
        <div class="event_preview">
          <div style="float:left; padding-right:15px;">
            <%= image_tag('defaultEvent.png') %>
          </div>
          <p class="title"><%= link_to event.title, event %></p>
              <p class="date"><%= event.date.strftime('%A, %B %-d at %l:%M %P') %></p>
              <div class="text"><%= simple_format(event.content) %></div>
              <% @ticket = Ticket.find_by_event_id(event.id) %>
              <% @keyword = @ticket.quantity.to_i == 1 ? 'ticket' : 'tickets' %>
              <div class="user_tickets">You have <%= @ticket.quantity %> <%= @keyword %> for this event.</div>
          </div>
    <% end %>
<% else %>
    <p>
      You haven't booked any events yet!
    </p>
<% end %>